import type { Donor, NGO, Listing, ImpactStats } from '@/types';

export const mockDonors: Donor[] = [
  {
    id: 'd1',
    name: 'Sharma Caterers',
    phone: '9876543210',
    area: 'Indirapuram',
    type: 'Caterer',
    reliabilityScore: 92,
    mealsRescued: 1240,
    joinedDate: '2025-08-15',
  },
  {
    id: 'd2',
    name: 'Royal Banquet Hall',
    phone: '9811122233',
    area: 'Vaishali',
    type: 'Banquet Hall',
    reliabilityScore: 88,
    mealsRescued: 890,
    joinedDate: '2025-07-20',
  },
  {
    id: 'd3',
    name: 'IIMT Hostel Mess',
    phone: '9988776655',
    area: 'Crossing Republik',
    type: 'Hostel Mess',
    reliabilityScore: 95,
    mealsRescued: 2100,
    joinedDate: '2025-06-10',
  },
];

export const mockNGOs: NGO[] = [
  {
    id: 'n1',
    name: 'Ashray Orphanage',
    phone: '9001234567',
    area: 'Indirapuram',
    type: 'Orphanage',
    registrationNumber: 'UP/GR/2018/04521',
    verified: true,
    reliabilityScore: 94,
    peopleCount: 45,
    foodPreference: ['veg', 'dry'],
    pickupWindow: '9 AM - 9 PM',
    mealsReceived: 1850,
    joinedDate: '2025-07-01',
  },
  {
    id: 'n2',
    name: 'Sahyog Shelter',
    phone: '9007654321',
    area: 'Vaishali',
    type: 'Shelter',
    registrationNumber: 'UP/GZ/2020/01189',
    verified: true,
    reliabilityScore: 89,
    peopleCount: 60,
    foodPreference: ['veg', 'non-veg', 'dry'],
    pickupWindow: '10 AM - 10 PM',
    mealsReceived: 1420,
    joinedDate: '2025-07-15',
  },
  {
    id: 'n3',
    name: 'Annapurna Food Bank',
    phone: '9112233445',
    area: 'Kaushambi',
    type: 'Food Bank',
    registrationNumber: 'UP/GZ/2021/03372',
    verified: true,
    reliabilityScore: 91,
    peopleCount: 100,
    foodPreference: ['veg', 'dry'],
    pickupWindow: '8 AM - 8 PM',
    mealsReceived: 2600,
    joinedDate: '2025-06-25',
  },
  {
    id: 'n4',
    name: 'Umeed Foundation',
    phone: '9334455667',
    area: 'Raj Nagar',
    type: 'Orphanage',
    registrationNumber: '',
    verified: false,
    reliabilityScore: 0,
    peopleCount: 30,
    foodPreference: ['veg'],
    pickupWindow: '10 AM - 7 PM',
    mealsReceived: 0,
    joinedDate: '2025-09-25',
  },
];

export const mockListings: Listing[] = [
  {
    id: 'l1',
    donorId: 'd1',
    donorName: 'Sharma Caterers',
    donorArea: 'Indirapuram',
    foodType: 'veg',
    foodDescription: 'Daal, chawal, sabzi, roti — shaadi ka bacha hua khana',
    quantityPeople: 80,
    status: 'ready',
    safeTill: new Date(Date.now() + 2 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
    safeHours: 2.5,
    area: 'Indirapuram',
    pickupMethod: 'ngo_pickup',
    pickupWindow: 'Abhi se 2 ghante tak',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    disclaimerAccepted: true,
    freshnessConfirmed: true,
    storageConfirmed: true,
    matchedNgoIds: ['n1', 'n3'],
  },
  {
    id: 'l2',
    donorId: 'd3',
    donorName: 'IIMT Hostel Mess',
    donorArea: 'Crossing Republik',
    foodType: 'veg',
    foodDescription: 'Mess ka khana — paneer, daal, chawal, poori',
    quantityPeople: 120,
    status: 'forecast',
    safeTill: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    safeHours: 4,
    area: 'Crossing Republik',
    pickupMethod: 'ngo_pickup',
    pickupWindow: 'Shaam 6 PM ke baad',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    disclaimerAccepted: true,
    freshnessConfirmed: true,
    storageConfirmed: true,
    matchedNgoIds: ['n1', 'n2', 'n3'],
  },
  {
    id: 'l3',
    donorId: 'd2',
    donorName: 'Royal Banquet Hall',
    donorArea: 'Vaishali',
    foodType: 'non-veg',
    foodDescription: 'Chicken curry, biryani, raita — event ka surplus',
    quantityPeople: 50,
    status: 'ready',
    safeTill: new Date(Date.now() + 1 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
    safeHours: 2,
    area: 'Vaishali',
    pickupMethod: 'donor_drop',
    pickupWindow: 'Abhi se 1.5 ghante tak',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    claimedByNgoId: 'n2',
    claimedByNgoName: 'Sahyog Shelter',
    handoverCode: '4729',
    claimedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    disclaimerAccepted: true,
    freshnessConfirmed: true,
    storageConfirmed: true,
    matchedNgoIds: ['n2'],
  },
];

export const mockImpact: ImpactStats = {
  mealsRescued: 8420,
  liveListings: 2,
  pickupsDone: 156,
  ngosActive: 3,
};
